INSERT INTO projeto_final.item(bolsa_id, tipo_item, descricao, preco, nome)
VALUES
(7, 'all-mail', 'Stationery featuring a print of atough-looking brick pattern.Let a Pokémon hold it for delivery.', 5.0, 'brick-mail'),
(1, 'vitamins', 'A candy that is packed with energy. When consumed,it will instantly raise the level of a single Pokémonby one.', 1000.0, 'rare-candy'),
(6, 'special-balls', 'A somewhat rare Poké Ball that was made as acommemorative item used to celebrate an event ofsome sort.', 2.0, 'premier-ball'),
(3, 'spelunking', 'A flute made from black glass. It makes it easier toencounter strong Pokémon in the place you use it.', 2.0, 'black-flute'),
(6, 'status-cures', 'A spray-type medicine for treating burns. It can beused to heal a single Pokémon suffering from a burn.', 20.0, 'burn-heal'),
(4, 'all-mail', 'Stationery featuring a print of giantheart patterns.Let a Pokémon hold it for delivery.', 5.0, 'heart-mail'),
(10, 'evolution', 'A peculiar stone that can make certain species ofPokémon evolve. It sparkles like a glittering eye.', 300.0, 'dawn-stone'),
(8, 'evolution', 'A peculiar stone that can make certain species ofPokémon evolve. It burns as red as the evening sun.', 300.0, 'sun-stone'),
(6, 'healing', 'An extremely bitter medicinal root. It can be used torestore 120 HP to a single Pokémon.', 120.0, 'energy-root'),
(8, 'evolution', 'A peculiar stone that can make certain species ofPokémon evolve. It has an unmistakable leaf pattern.', 300.0, 'leaf-stone'),
(8, 'vitamins', 'A medicine that optimally raises the max PP of a singleselected move that has been learned by a Pokémon.', 1000.0, 'pp-max'),
(1, 'all-mail', 'Stationery featuring a print ofcolorful letter sets.Let a Pokémon hold it for delivery.', 5.0, 'air-mail'),
(6, 'special-balls', 'A somewhat rare Poké Ball that was made as acommemorative item used to celebrate an event ofsome sort.', 2.0, 'premier-ball'),
(9, 'status-cures', 'A very bitter medicinal powder. It can be used onceto heal all the status conditions of a Pokémon.', 30.0, 'heal-powder'),
(4, 'loot', 'A nugget of the purest gold that gives off a lustrousgleam in direct light. It can be sold at a high priceto shops.', 1000.0, 'nugget'),
(1, 'healing', 'A bottle of highly nutritious milk. It can be used torestore 100 HP to a single Pokémon.', 60.0, 'moomoo-milk'),
(11, 'special-balls', 'A somewhat different Poké Ball that is moreeffective when attempting to catch Water- orBug-type Pokémon.', 100.0, 'net-ball'),
(3, 'mulch', 'A fertilizer for growing Berries. However, it appearsto be unsuitable for the soil in the Hoenn region andhas no effect.', 20.0, 'stable-mulch'),
(4, 'special-balls', 'A somewhat different Poké Ball that has a moresuccessful catch rate if used at the start of awild encounter.', 100.0, 'quick-ball'),
(3, 'revival', 'A medicine that can be used to revive a singlePokémon that has fainted. It also fully restoresthe Pokémon’s max HP.', 400.0, 'max-revive'),
(1, 'all-mail', 'Stationery featuring a print depictingthe huge expanse of space.Let a Pokémon hold it for delivery.', 5.0, 'space-mail'),
(5, 'status-cures', 'A spray-type medicine for treating burns. It can beused to heal a single Pokémon suffering from a burn.', 20.0, 'burn-heal'),
(9, 'special-balls', 'A quite rare Poké Ball that has been crafted inorder to commemorate a special occasion ofsome sort.', 0.0, 'cherish-ball'),
(2, 'mulch', 'A fertilizer for growing Berries. However, it appearsto be unsuitable for the soil in the Hoenn region andhas no effect.', 20.0, 'stable-mulch'),
(10, 'healing', 'A spray-type medicine for treating wounds. It canbe used to restore 20 HP to a single Pokémon.', 20.0, 'potion'),
(6, 'healing', 'A very sweet and refreshing drink. It can be used torestore 70 HP to a single Pokémon.', 40.0, 'lemonade'),
(4, 'dex-completion', 'A fossil from a prehistoric Pokémon that once livedin the sea. It appears to be a fragment of a claw.', 700.0, 'claw-fossil'),
(6, 'revival', 'This rare ash can revive all fainted Pokémon in aparty. In doing so, it also fully restores their max HP.', 5000.0, 'sacred-ash'),
(7, 'dex-completion', 'A sweet honey collected by Pokémon. It has a lusharoma and can be sold at a low price to shops.', 90.0, 'honey'),
(10, 'standard-balls', 'An ultra-high-performance Poké Ball that providesa higher success rate for catching Pokémon thana Great Ball.', 80.0, 'ultra-ball'),
(12, 'stat-boosts', 'An item that sharply boosts the Defense stat of aPokémon during a battle. It wears off once thePokémon is withdrawn.', 200.0, 'x-defense'),
(8, 'healing', 'A medicine that can be used to fully restore the HP ofa single Pokémon and heal any status conditions it has.', 300.0, 'full-restore'),
(1, 'all-mail', 'Stationery featuring a print ofcolorful letter sets.Let a Pokémon hold it for delivery.', 5.0, 'air-mail'),
(8, 'special-balls', 'A somewhat different Poké Ball that has a moresuccessful catch rate if used at the start of awild encounter.', 100.0, 'quick-ball'),
(5, 'stat-boosts', 'An item that sharply boosts the Speed stat of aPokémon during a battle. It wears off once thePokémon is withdrawn.', 100.0, 'x-speed'),
(5, 'loot', 'A rare bone that is extremely valuable for thestudy of Pokémon archeology. It can be sold for ahigh price to shops.', 500.0, 'rare-bone'),
(11, 'dex-completion', 'A piece of amber that still contains the geneticmaterial of an ancient Pokémon. It’s clear with atawny, reddish tint.', 1000.0, 'old-amber'),
(6, 'vitamins', 'A candy that is packed with energy. When consumed,it will instantly raise the level of a single Pokémonby one.', 1000.0, 'rare-candy'),
(9, 'dex-completion', 'A fossil from a prehistoric Pokémon that once livedin the sea. It appears to be a fragment of a claw.', 700.0, 'claw-fossil'),
(9, 'healing', 'A spray-type medicine for treating wounds. It canbe used to restore 20 HP to a single Pokémon.', 20.0, 'potion'),
(9, 'revival', 'A medicine that can be used to revive a singlePokémon that has fainted. It also restores half ofthe Pokémon’s max HP.', 200.0, 'revive'),
(10, 'loot', 'Lovely red sand that flows between the fingerswith a loose, silky feel. It can be sold at a low priceto shops.', 300.0, 'stardust'),
(3, 'vitamins', 'A medicine that slightly raises the max PP of a singleselected move that has been learned by a Pokémon.', 1000.0, 'pp-up'),
(6, 'dex-completion', 'A fossil from a prehistoric Pokémon that once livedin the sea. It might be a piece of a seashell.', 700.0, 'helix-fossil'),
(9, 'vitamins', 'A medicine that optimally raises the max PP of a singleselected move that has been learned by a Pokémon.', 1000.0, 'pp-max'),
(10, 'medicine', 'A Berry to be consumed by Pokémon. If a Pokémonholds one, it can recover from paralysis on its ownin battle.', 8.0, 'cheri-berry'),
(12, 'healing', 'A bottle of highly nutritious milk. It can be used torestore 100 HP to a single Pokémon.', 60.0, 'moomoo-milk'),
(5, 'all-mail', 'Stationery featuring a print of giantheart patterns.Let a Pokémon hold it for delivery.', 5.0, 'heart-mail'),
(1, 'dex-completion', 'A fossil from a prehistoric Pokémon that once livedin the sea. It might be a piece of a seashell.', 700.0, 'helix-fossil'),
(7, 'special-balls', 'A somewhat rare Poké Ball that was made as acommemorative item used to celebrate an event ofsome sort.', 2.0, 'premier-ball');