INSERT INTO PROJETO_FINAL.BATALHA (GINASIO_ID, DATA, VENCEDOR_ID)
VALUES
    (NULL, '2023-12-15', 13);

INSERT INTO PROJETO_FINAL.TREINADOR (REGIAO_ID, NOME, SEXO, IDADE)
VALUES
    (1, 'Ash', 'M', 25),
    (2, 'Red', 'F', 30);	
INSERT INTO PROJETO_FINAL.TREINADOR_BATALHA (TREINADOR_ID, BATALHA_ID)
VALUES
    (13, 18),
    (14, 18);