DROP SCHEMA IF EXISTS projeto_final CASCADE;

CREATE SCHEMA projeto_final;

-- TABELA POKEMON_TIME
CREATE TABLE PROJETO_FINAL.POKEMON_TIME(
	POKEMON_ID INT PRIMARY KEY,
  	TIME_ID INT NOT NULL
);

-- TABELA TIME
CREATE TABLE PROJETO_FINAL.TIME(
	TIME_ID SERIAL PRIMARY KEY
);

-- TABELA POKEDEX
CREATE TABLE PROJETO_FINAL.POKEDEX(
	POKEDEX_ID SERIAL PRIMARY KEY,
  	DESCRICAO VARCHAR(200)
);

-- TABELA POKEMON
CREATE TABLE PROJETO_FINAL.POKEMON(
	POKEMON_ID SERIAL PRIMARY KEY,
  	POKEDEX_ID INT NOT NULL,
  	NOME VARCHAR(60),
  	LVL INT NOT NULL,
  	ATK INT NOT NULL,
  	DEF INT NOT NULL,
  	SP_DEF INT NOT NULL,
  	SP_ATK INT NOT NULL,
  	VEL INT NOT NULL,
  	HP INT NOT NULL
);

--TABELA TREINADOR_TIME
CREATE TABLE PROJETO_FINAL.TREINADOR_TIME(
	TREINADOR_ID INT PRIMARY KEY,
  	TIME_ID INT NOT NULL
);

-- TABELA REGIAO
CREATE TABLE PROJETO_FINAL.REGIAO(
	REGIAO_ID SERIAL PRIMARY KEY,
  	NOME VARCHAR(100),
  	DESCRICAO VARCHAR(100)
);

-- TABELA TREINADOR
CREATE TABLE PROJETO_FINAL.TREINADOR(
	TREINADOR_ID SERIAL PRIMARY KEY,
  	REGIAO_ID INT NOT NULL,
  	NOME VARCHAR(100),
  	SEXO CHAR,
  	IDADE INT
);


-- TABELA BOLSA
CREATE TABLE PROJETO_FINAL.BOLSA (
	BOLSA_ID SERIAL PRIMARY KEY,
  	COR VARCHAR(20),
  	MODELO CHAR
);


-- TABELA ITEM
CREATE TABLE PROJETO_FINAL.ITEM (
	ITEM_ID SERIAL PRIMARY KEY,
  	BOLSA_ID INT NOT NULL,
  	TIPO_ITEM VARCHAR(20),
  	DESCRICAO VARCHAR(255),
  	PRECO NUMERIC(10,2) NOT NULL,
	NOME VARCHAR(60)
);

-- TABELA TREINADOR BOLSA
CREATE TABLE PROJETO_FINAL.TREINADOR_BOLSA (
	TREINADOR_ID INT PRIMARY KEY,
  	BOLSA_ID INT NOT NULL
);

-- TABELA TIPO POKEMON
CREATE TABLE PROJETO_FINAL.TIPO_POKEMON (
	TIPO_POKEMON_ID SERIAL PRIMARY KEY,
  	DESCRICAO VARCHAR(255),
  	NOME_TIPO VARCHAR(30) NOT NULL
);

-- TABELA POKEMON TIPO POKEMON
CREATE TABLE PROJETO_FINAL.POKEMON_TIPO_POKEMON (
	POKEMON_ID INT NOT NULL,
  	TIPO_POKEMON_ID INT NOT NULL,
	PRIMARY KEY (POKEMON_ID, TIPO_POKEMON_ID)
);

-- TABELA MOVE 
CREATE TABLE PROJETO_FINAL.MOVE (
	MOVE_ID SERIAL PRIMARY KEY,
  	CATEGORIA VARCHAR(20),
  	DESCRICAO VARCHAR(200),
  	PODER INT,
  	PRECISAO INT,
	NOME VARCHAR(50)
);

-- TABELA POKEMON_MOVE 
CREATE TABLE PROJETO_FINAL.POKEMON_MOVE (
	POKEMON_ID INT NOT NULL,
  	MOVE_ID INT NOT NULL,
	PRIMARY KEY (POKEMON_ID, MOVE_ID)
);

-- TABELA GINASIO
CREATE TABLE PROJETO_FINAL.GINASIO (
	GINASIO_ID SERIAL PRIMARY KEY,
  	REGIAO_ID INT NOT NULL,
  	NOME VARCHAR(50)
);

-- TABELA BATALHA 
CREATE TABLE PROJETO_FINAL.BATALHA (
	BATALHA_ID SERIAL PRIMARY KEY,
  	GINASIO_ID INT,
  	DATA DATE,
  	VENCEDOR_ID INT NOT NULL
);

-- TABELA TREINADOR_BATALHA 
CREATE TABLE PROJETO_FINAL.TREINADOR_BATALHA (
	BATALHA_ID INT NOT NULL,
  	TREINADOR_ID INT NOT NULL,
  	PRIMARY KEY (BATALHA_ID, TREINADOR_ID)
);


-- Restrições de Chave Estrangeira para a Tabela POKEMON_TIME
ALTER TABLE PROJETO_FINAL.POKEMON_TIME
ADD CONSTRAINT FK_POKEMON_TIME_TIME
FOREIGN KEY (TIME_ID) REFERENCES PROJETO_FINAL.TIME(TIME_ID);

-- Restrições de Chave Estrangeira para a Tabela POKEMON_TIME
ALTER TABLE PROJETO_FINAL.POKEMON_TIME
ADD CONSTRAINT FK_POKEMON_POKEMON_ID
FOREIGN KEY (POKEMON_ID) REFERENCES PROJETO_FINAL.POKEMON(POKEMON_ID);

-- Restrições de Chave Estrangeira para a Tabela POKEMON
ALTER TABLE PROJETO_FINAL.POKEMON
ADD CONSTRAINT FK_POKEMON_POKEDEX
FOREIGN KEY (POKEDEX_ID) REFERENCES PROJETO_FINAL.POKEDEX(POKEDEX_ID);

-- Restrições de Chave Estrangeira para a Tabela TREINADOR_TIME
ALTER TABLE PROJETO_FINAL.TREINADOR_TIME
ADD CONSTRAINT FK_TREINADOR_TIME_TIME
FOREIGN KEY (TIME_ID) REFERENCES PROJETO_FINAL.TIME(TIME_ID);

-- Restrições de Chave Estrangeira para a Tabela TREINADOR_TIME
ALTER TABLE PROJETO_FINAL.TREINADOR_TIME
ADD CONSTRAINT FK_TREINADOR_TIME_TREINADOR_ID
FOREIGN KEY (TREINADOR_ID) REFERENCES PROJETO_FINAL.TREINADOR(TREINADOR_ID);

-- Restrições de Chave Estrangeira para a Tabela TREINADOR
ALTER TABLE PROJETO_FINAL.TREINADOR
ADD CONSTRAINT FK_TREINADOR_REGIAO
FOREIGN KEY (REGIAO_ID) REFERENCES PROJETO_FINAL.REGIAO(REGIAO_ID);

-- Restrições de Chave Estrangeira para a Tabela TREINADOR_BOLSA
ALTER TABLE PROJETO_FINAL.TREINADOR_BOLSA
ADD CONSTRAINT FK_TREINADOR_BOLSA_BOLSA
FOREIGN KEY (BOLSA_ID) REFERENCES PROJETO_FINAL.BOLSA(BOLSA_ID);

-- Restrições de Chave Estrangeira para a Tabela TREINADOR_BOLSA
ALTER TABLE PROJETO_FINAL.TREINADOR_BOLSA
ADD CONSTRAINT FK_TREINADOR_BOLSA_TREINADOR_ID
FOREIGN KEY (TREINADOR_ID) REFERENCES PROJETO_FINAL.TREINADOR(TREINADOR_ID);

-- Restrições de Chave Estrangeira para a Tabela ITEM
ALTER TABLE PROJETO_FINAL.ITEM
ADD CONSTRAINT FK_ITEM_BOLSA
FOREIGN KEY (BOLSA_ID) REFERENCES PROJETO_FINAL.BOLSA(BOLSA_ID);

-- Restrições de Chave Estrangeira para a Tabela POKEMON_TIPO_POKEMON
ALTER TABLE PROJETO_FINAL.POKEMON_TIPO_POKEMON
ADD CONSTRAINT FK_POKEMON_TIPO_POKEMON_TIPO_POKEMON
FOREIGN KEY (TIPO_POKEMON_ID) REFERENCES PROJETO_FINAL.TIPO_POKEMON(TIPO_POKEMON_ID);

-- Restrições de Chave Estrangeira para a Tabela POKEMON_TIPO_POKEMON
ALTER TABLE PROJETO_FINAL.POKEMON_TIPO_POKEMON
ADD CONSTRAINT FK_POKEMON_TIPO_POKEMON_POKEMON
FOREIGN KEY (POKEMON_ID) REFERENCES PROJETO_FINAL.POKEMON(POKEMON_ID);

-- Restrições de Chave Estrangeira para a Tabela POKEMON_MOVE
ALTER TABLE PROJETO_FINAL.POKEMON_MOVE
ADD CONSTRAINT FK_POKEMON_MOVE_MOVE
FOREIGN KEY (MOVE_ID) REFERENCES PROJETO_FINAL.MOVE(MOVE_ID);

-- Restrições de Chave Estrangeira para a Tabela POKEMON_MOVE
ALTER TABLE PROJETO_FINAL.POKEMON_MOVE
ADD CONSTRAINT FK_POKEMON_MOVE_POKEMON
FOREIGN KEY (POKEMON_ID) REFERENCES PROJETO_FINAL.POKEMON(POKEMON_ID);

-- Restrições de Chave Estrangeira para a Tabela BATALHA
ALTER TABLE PROJETO_FINAL.BATALHA
ADD CONSTRAINT FK_BATALHA_GINASIO
FOREIGN KEY (GINASIO_ID) REFERENCES PROJETO_FINAL.GINASIO(GINASIO_ID);

-- Restrições de Chave Estrangeira para a Tabela BATALHA
ALTER TABLE PROJETO_FINAL.BATALHA
ADD CONSTRAINT FK_BATALHA_TREINADOR
FOREIGN KEY (VENCEDOR_ID) REFERENCES PROJETO_FINAL.TREINADOR(TREINADOR_ID);

-- Restrições de Chave Estrangeira para a Tabela BATALHA
ALTER TABLE PROJETO_FINAL.BATALHA
ADD CONSTRAINT FK_BATALHA_GINASIO_ID
FOREIGN KEY (GINASIO_ID) REFERENCES PROJETO_FINAL.GINASIO(GINASIO_ID);

-- Restrições de Chave Estrangeira para a Tabela TREINADOR_BATALHA
ALTER TABLE PROJETO_FINAL.TREINADOR_BATALHA
ADD CONSTRAINT FK_TREINADOR_BATALHA_BATALHA
FOREIGN KEY (BATALHA_ID) REFERENCES PROJETO_FINAL.BATALHA(BATALHA_ID);

-- Restrições de Chave Estrangeira para a Tabela TREINADOR_BATALHA
ALTER TABLE PROJETO_FINAL.TREINADOR_BATALHA
ADD CONSTRAINT FK_TREINADOR_BATALHA_TREINADOR
FOREIGN KEY (TREINADOR_ID) REFERENCES PROJETO_FINAL.TREINADOR(TREINADOR_ID);